import com.currenciesdirect.gtg.compliance.core.globalcheck.staterulecheck.StateParam;
rule "US-CLEAR" 
    dialect "java"
    when 
        m:StateParam (
            organizationCode != "CD SA"
            &&
            isoAlpha3CountryCode == "USA"
            &&
            (stateName in 
            	("GEORGIA", "FLORIDA", "MONTANA",  
            	"NORTH CAROLINA", "WISCONSIN")
            )
        ) 
    then 
        m.setResult("PASS");
end;

rule "US-WATCH_LIST" 
    dialect "java"
    when 
        m:StateParam (
            organizationCode != "CD SA"
            &&
            isoAlpha3CountryCode == "USA"
            &&
            (stateName in 
            	("ALABAMA", "CALIFORNIA", "CONNECTICUT", "DELAWARE", "HAWAII", "IDAHO",
            	"INDIANA", "KANSAS", "KENTUCKY", "LOUISIANA", "MARYLAND"
            	,"MASSACHUSETTS", "MICHIGAN", "MINNESOTA", "MISSISSIPPI",
            	"MISSOURI", "NEBRASKA", "NEVADA", "NEW HAMPSHIRE", "NEW JERSEY",
            	"NEW YORK", "PUERTO RICO", "NORTH DAKOTA", "OREGON", "SOUTH DAKOTA",
            	"TENNESSEE", "UTAH", "VIRGINIA", "WYOMING", "DISTRICT OF COLUMBIA",
            	"AMERICAN SAMOA")
            )
        ) 
    then 
        m.setResult("WATCH_LIST");
end;

rule "US-REJECT" 
    dialect "java"
    when 
        m:StateParam (
            organizationCode != "CD SA"
            &&
            isoAlpha3CountryCode == "USA"
            &&
            (stateName in 
            	("ARKANSAS", "ALASKA", "ARIZONA", "COLORADO", "IOWA",
            	"MAINE", "OHIO", "OKLAHOMA", "VERMONT",
            	"WASHINGTON", "WEST VIRGINIA", "GUAM", "NORTHERN MARIANA ISLANDS",
            	"U.S. VIRGIN ISLANDS", "NEW MEXICO")
            )
        ) 
    then 
        m.setResult("FAIL");
end;

rule "US-CDINC-WA-CLEAR" 
    dialect "java"
    when 
        m:StateParam (
            organizationCode != "CD SA"
            &&
            isoAlpha3CountryCode == "USA"
            &&
            orgLegalEntity == "CDINC"
            &&
            stateName in ("WASHINGTON", "NEW JERSEY", 
            	"ILLINOIS", "RHODE ISLAND", "TEXAS", "PENNSYLVANIA", "SOUTH CAROLINA","CALIFORNIA")
        )
    then 
        m.setResult("PASS");
end;
