package com.currenciesdirect.gtg.compliance.dbport.report;

import com.currenciesdirect.gtg.compliance.util.SearchCriteriaUtil;

/**
 * The Enum PaymentInQueryConstant.
 *
 * @author Rajesh
 */
@SuppressWarnings({"squid:S1192","squid:S1192"})
public enum PaymentInReportQueryConstant {	
	
	PAYMENTIN_REPORT_CONTACT_ATTRIBUTE_FILTER( "SELECT   b.accountid , a.id contactid, Row_number() OVER (partition BY b.accountid ORDER BY b.updatedon) rnum "
			+ "   FROM contactattribute A JOIN contact B ON a.id = b.id {WATCHLIST_CATEGORY_FILTER} {WATCHLIST_FILTER} {PAYMENTIN_REPORT_COUNTRY_OF_RESIDENCE_FILTER} "),
	
	WATCHLIST_FILTER(" EXISTS( SELECT 1 FROM ContactWatchList CL WHERE Reason IN(?) AND a.id = CL.contact ) "),
	WATCHLIST_CATEGORY_FILTER(" LEFT JOIN ContactWatchList CL ON CL.contact=B.id JOIN watchlist W ON CL.reason=w.id AND w.category IN(?)  "),
	
	PAYMENTIN_REPORT_ACCOUNT_ATTRIBUTE_FILTER( "  SELECT a.id accountid, b.organizationId as organization  "
			+ " FROM   accountattribute A  JOIN account B  ON  a.id = b.id"),
	
	PAYMENTIN_REPORT_ATTRIBUTE_FILTER(" SELECT p.id AS paymentid  FROM   comp.paymentinattribute P " 
			+ "{COUNTRY_JOIN} "),
	
	PAYMENTIN_REPORT_FILTER(" SELECT  payin.id AS resourceid,  resourcetype, ur.createdby "
			/*
			 * +
			 * " (SELECT	se.status FROM ServiceStatusEnum se WHERE se.ID = esl.Status) AS ESLRiskStatus "
			 */
			+ " FROM   paymentin payin " //,  U.SsoUserId
			+ " LEFT JOIN userresourcelock ur  ON  ur.resourceid = payin.id  AND resourcetype = 2 AND ur.lockReleasedOn is null "
			/*
			 * +
			 * " LEFT JOIN eventservicelog esl ON esl.EntityID = payin.ID AND esl.ServiceType = 11"
			 */
			+ " {CONTACT_FILTER_JOIN} {ACCOUNT_FILTER_JOIN} {ATTRIBUTE_FILTER_JOIN} {USER_JOIN} {ORG_TABLE_JOIN} {LEGAL_ENTITY_TABLE_JOIN} JOIN Account acc ON payin.accountid = acc.id "), 
	
	PAYMENTIN_REPORT_CONTACT_FILTER_JOIN(" LEFT JOIN  contactattributefilter CF ON payin.contactid = cf.contactid"),
	
	PAYMENTIN_REPORT_ACCOUNT_FILTER_JOIN(" LEFT JOIN  accountattributefilter AF ON payin.accountid = af.accountid"),
	
	PAYMENTIN_REPORT_ATTRIBUTE_FILTER_JOIN(" JOIN paymentattributefilter PF ON payin.id = PF.paymentid"),
	
	ORG_TABLE_JOIN("JOIN Organization org ON org.Id = payin.organizationID  "),
	
	LEGAL_ENTITY_TABLE_JOIN("JOIN LegalEntity le ON le.ID = payin.LegalEntityID"),
	
	USER_FILTER_JOIN("LEFT JOIN [USER] U ON U.id=ur.UserId "),
	
	COUNTRY_FILTER_JOIN("LEFT JOIN  country c ON c.code=P.vCountryOfPayment"),
	
	RG_FILTER_JOIN("LEFT JOIN eventservicelog esl ON esl.EntityID = payin.ID AND esl.ServiceType = 11"),

	REPORT_FILTER_NULL_CHECK(" (CF.ContactId IS NOT NULL OR AF.AccountId IS NOT NULL) "),
	
	PAYMENTIN_REPORT_COUNTRY_OF_RESIDENCE_FILTER("JOIN country cor ON cor.id = b.country"),
	
	GET_PAYMENTIN_REPORT(" DECLARE @Offset INT = ?,   @Rows   INT = ?;"
			+ "  WITH "
			+ " contactattributefilter "
			+ " AS ( {PAYMENTIN_REPORT_CONTACT_FILTER} ), "
			+ " accountattributefilter "
			+ " AS ( {PAYMENTIN_REPORT_ACCOUNT_FILTER} ), "
			+ " paymentattributefilter "
			+ " AS ( {PAYMENTIN_ATTRIBUTE_FILTER} ), "
			+ " selectedid AS (  {PAYMENTIN_REPORT_FILTER} order by {SORT_FIELD_NAME} {ORDER_TYPE} offset @Offset rows  FETCH next @rows rows only ) "
			+ " SELECT    pina.attributes, "
			+ "          payin.id               AS paymentinid, "
			+ "          payin.accountid        AS accountid, "
			+ "          payin.contactid        AS contactid, "
			+ "          payin.compliancestatus AS compliancestatus, "
			+ "          payin.tradeContractNumber   AS transactions, "
			+ "          acc.tradeaccountnumber  AS client, "
			+ "          acc.crmaccountid        AS acsfid, "
			+ "          payin.transactiondate  AS [Date], "
			+ "          acc.[type] AS type, "
			+ "          CASE WHEN acc.[type] = 2 THEN con.NAME ELSE acc.NAME "
			+ "          END                                               AS clientname, "
			+ "          pina.vTransactionCurrency                         AS transactioncurrency, "
			+ "          pina.vTransactionAmount                           AS amount, "
			+ "          pina.vBaseCurrencyAmount                          AS basecurrencyamount, "
			+ "          pina.vPaymentMethod  AS paymentmethod, "
			+ "          pina.vThirdPartyPayment                           AS isthirdpartypayment, "
			+ "          resourceid, "
			+ "          us.ssouserid  AS lockedby, "
			+ "          org.NAME AS organization, "
			+ "          acc.LegalEntity, "
			+ "          pina.vCountryOfPayment  AS country, "
			+ "          coun.DisplayName                     AS countrydisplayname,"
			+ "          pcse.status  AS overallstatus, "
			+ "          CASE "
			+ "          WHEN acc.[type] = 2 THEN con.PayInwatchliststatus "
			+ "          ELSE acc.PayInwatchliststatus END AS WatchListStatus, "//changes for 2986
			+ "          payin.blackliststatus, "
			+ "          payin.fraugsterstatus, "
			+ "          payin.sanctionstatus, "
			+ "          payin.customcheckstatus, "
			+ "          payin.intuitionCheckStatus, " // AT-4607
			+ "          payin.debitCardFraudCheckStatus AS riskStatus" //AT-3830
			+ " FROM     paymentin payin "
			+ " JOIN     selectedid pq "
			+ " ON       pq.resourceid = payin.id "
			+ " JOIN     paymentinattribute pina "
			+ " ON       payin.id = pina.id "
			+ " JOIN     paymentcompliancestatusenum pcse "
			+ " ON       payin.compliancestatus = pcse.id "
			+ " JOIN     account acc "
			+ " ON       payin.accountid = acc.id "
			+ " JOIN     contact con "
			+ " ON       payin.contactid = con.id "
			+ " JOIN     organization org "
			+ " ON       org.id = acc.organizationid "
			+ " LEFT JOIN country coun "
			+ " ON       coun.code = pina.vcountryofpayment "
			+ " LEFT JOIN [user] us ON us.id = pq.createdby "
			+ " order by {SORT_FIELD_NAME} {ORDER_TYPE}"),
	
	GET_PAYMENTIN_REPORT_DATA( " WITH "
			+ " contactattributefilter AS ( {PAYMENTIN_REPORT_CONTACT_FILTER} ), "
			+ " accountattributefilter AS ( {PAYMENTIN_REPORT_ACCOUNT_FILTER} ), "
			+ " paymentattributefilter AS ( {PAYMENTIN_ATTRIBUTE_FILTER} ), "
			+ " selectedid AS (  {PAYMENTIN_REPORT_FILTER} ) "
			+ " SELECT    pina.attributes, "
			+ "          payin.id               AS paymentinid, "
			+ "          payin.accountid        AS accountid, "
			+ "          payin.contactid        AS contactid, "
			+ "          payin.compliancestatus AS compliancestatus, "
			+ "          payin.tradeContractNumber   AS transactions, "
			+"            payin.initialStatus  AS initialStatus, "
			+ "          acc.tradeaccountnumber  AS client, "
			+ "          acc.crmaccountid        AS acsfid, "
			+ "          payin.transactiondate  AS [Date], "
			+ "          CASE "
			+ "                    WHEN acc.[type] = 2 THEN 'PFX' "
			+ "                    WHEN acc.[type] = 1 THEN 'CFX' "
			+ "                    ELSE 'CFX(Etailer)' "
			+ "          END AS type, "
			+ "          CASE "
			+ "                    WHEN acc.[type] = 2 THEN con.NAME "
			+ "                    ELSE acc.NAME "
			+ "          END                                               AS clientname, "
			+ "          pina.vTransactionCurrency                         AS transactioncurrency, "
			+ "          pina.vTransactionAmount                           AS amount, "
			+ "          pina.vBaseCurrencyAmount                          AS basecurrencyamount, "
			+ "          pina.vPaymentMethod   AS paymentmethod, "
			+ "          pina.vThirdPartyPayment                           AS isthirdpartypayment, "
			+ "          resourceid, "
			+ "          us.ssouserid  AS lockedby, "
			+ "          org.NAME  AS organization, "
			+ "          acc.LegalEntity, " //added for AT-3011
			+ "          pina.vCountryOfPayment  AS country, "
			+ "          coun.DisplayName                  AS countrydisplayname,"
			+ "          pcse.status  AS overallstatus, "
			+ "          acc.PayInwatchliststatus  AS watchliststatus, "
			+ "          payin.blackliststatus, "
			+ "          payin.fraugsterstatus, "
			+ "          payin.sanctionstatus, "
			+ "          payin.customcheckstatus ," 
			+ "          payin.debitCardFraudCheckStatus AS riskStatus," //AT-3830
			+ "          payin.IntuitionCheckStatus " //AT-4717
			+ " FROM      paymentin payin "
			+ " JOIN      selectedid pq "
			+ " ON        pq.resourceid = payin.id "
			+ " JOIN      paymentinattribute pina "
			+ " ON        payin.id = pina.id "
			+ " JOIN      paymentcompliancestatusenum pcse "
			+ " ON        payin.compliancestatus = pcse.id "
			+ " JOIN      account acc "
			+ " ON        payin.accountid = acc.id "
			+ " JOIN      contact con "
			+ " ON        payin.contactid = con.id "
			+ " JOIN      organization org "
			+ " ON        org.id = acc.organizationid "
			+ " LEFT JOIN country coun "
			+ " ON        coun.code = pina.vcountryofpayment "
			+ " LEFT JOIN [user] us "
			+ " ON        us.id = pq.createdby order by {SORT_FIELD_NAME} {ORDER_TYPE}"),
	
	PAYMENTIN_REPORT_COUNT("WITH "
			+ " contactattributefilter AS ( {PAYMENTIN_REPORT_CONTACT_FILTER} ), "
			+ " accountattributefilter AS ( {PAYMENTIN_REPORT_ACCOUNT_FILTER} ), "
			+ " paymentattributefilter AS ( {PAYMENTIN_ATTRIBUTE_FILTER} ), "
			+ " selectedid AS (  {PAYMENTIN_REPORT_FILTER}  ) " //ORDER BY  payin.updatedon DESC offset @Offset rows  FETCH next @rows rows only
			+ " SELECT   Count(payin.Id)              AS TotalRows "
			+ " FROM      paymentin payin "
			+ " JOIN      selectedid pq "
			+ " ON        pq.resourceid = payin.id "
			+ " JOIN      paymentinattribute pina "
			+ " ON        payin.id = pina.id "
			+ " JOIN      paymentcompliancestatusenum pcse "
			+ " ON        payin.compliancestatus = pcse.id "
			+ " JOIN      account acc "
			+ " ON        payin.accountid = acc.id "
			+ " JOIN      contact con "
			+ " ON        payin.contactid = con.id "
			+ " JOIN      organization org "
			+ " ON        org.id = acc.organizationid "
			+ " LEFT JOIN [user] us "
			+ " ON        us.id = pq.createdby"),
	
	GET_PAYMENTIN_REPORT_PAGINATION("WITH pique AS( "
			+ " SELECT "
			+ " Row_number() OVER(ORDER BY payin.id DESC) AS rownum, "
			+ " payin.id AS paymentinid, "
			+ " payin.accountid AS accountid, "
			+ " payin.contactid AS contactid, "
			+ " payin.compliancestatus AS compliancestatus, "
			+ " payin.deleted AS deleted, "
			+ " payin.tradecontractnumber AS Transactions, "
			+ " acc.tradeaccountnumber AS client, "
			+ " payinattri.transactiondate AS [Date], "
			+ " acc.[type] AS [type], "
			+ "         case when  acc.[type]='PFX' then con.NAME when acc.[type]='CFX' then acc.NAME "
			+ " END as clientname,"
			+ " payinattri.transactioncurrency AS sell, "
			+ " payinattri.transactionamount AS amount, "
			+ " payinattri.paymentmethod AS [method], "
			+ " ur.id AS resourceid, "
			+ " us.ssouserid AS lockedby, "
			+ " org.NAME AS organization, "
			+ " ( Select ','+(select wl.reason AS WatchListReason from WatchList wl where id=cw.Reason)  AS [text()] "
			+ " From contactwatchlist cw JOIN contact con ON cw.contact=con.id AND con.accountid = payin.accountid "
			+ " For XML PATH ('') ) AS WatchListReason, "
			+ " ctr.code AS country, "
			+ " pcse.status AS overallstatus, "
			+ " acc.WatchlistStatus AS watchliststatus, "
			+ " payin.BlacklistStatus AS blackliststatus, "
			+ " payin.FraugsterStatus AS fraugsterstatus, "
			+ " payin.SanctionStatus AS sanctionstatus, "
			+ " payin.CustomCheckStatus AS CustomCheckStatus "
			+ " FROM "
			+ " paymentin payIn "
			+ " JOIN paymentinattribute payInAttri ON payin.id = payinattri.id "
			+ " JOIN account acc ON payin.accountid = acc.id "
			+ " JOIN contact con ON payin.contactid = con.id "
			+ " JOIN paymentcompliancestatusenum pcse ON payin.compliancestatus = pcse.id "
			+ " JOIN Country ctr ON payInAttri.countryofpayment = ctr.id "
			+ " JOIN organization org ON org.id = acc.organizationid "
			+ " LEFT JOIN userresourcelock ur ON payin.id = ur.resourceid "
			+ " AND ur.resourcetype = 'PAYMENT_IN' "
			+ " LEFT JOIN [user] us ON us.id = ur.createdby "
			+ " WHERE "
			+ " payinattri.transactiondate > DATEADD(day,-" + SearchCriteriaUtil.getDefaultQueueRecordSize() + ",GETDATE()) "
			+ " AND payIn.deleted = 0 "
			+ ") "
			+ "SELECT *, (SELECT max(rownum) FROM pique) AS 'TotalRows' "
			+ "FROM "
			+ " pique "
			+ "WHERE "
			+ " rownum >= ? "
			+ " AND rownum <= ? "),
	
	GET_PAYMENTIN_REPORT_COUNT("SELECT COUNT(*) as count FROM PaymentIn"),
	
	GET_PAYMENTIN_REPORT_WITHOUT_PAGINATION("SELECT Count(*) AS count from( SELECT * FROM "
			+ "                      (SELECT payin.id AS paymentinid, "
			+ "                      payin.accountid  AS   accountid  , "
			+ "                      payin.contactid AS contactid, "
			+ "                       "
			+ "                      (select ssouserid from [user] where id=ur.userid) as username, "
			+ "                      payin.compliancestatus AS   compliancestatus, "
			+ "                      statusEnum.status AS compliancestatusenum, "
			+ "                      payin.deleted   AS  deleted, "
			+ "                      payin.tradecontractnumber   AS   Transactions, "
			+ "                      acc.tradeaccountnumber AS  client, "
			+ "                       acc.CRMAccountID AS ACSFID, "
			+ "                       conattrib.Attributes    AS ContactAttributes, "
			+ "                      payinattri.transactiondate AS [Date], "
			+ "                      acc.type  AS   type, "
			+ "                       case when  acc.[type]='PFX' then con.NAME when acc.[type]='CFX' then acc.NAME "
			+ "                       END as clientname,"
			+ "                      payinattri.transactioncurrency  AS  sell, "
			+ "                      payinattri.transactionamount  AS  amount, "
			+ "                      payinattri.paymentmethod AS   method, "
			+ "                        "
			+ "                      ur.id  AS  resourceid, "
			+ "                      (select ssouserid from [user] where id = ur.createdby)   AS    lockedby, "
			+ "                     ( Select ','+(select wl.reason AS WatchListReason from WatchList wl where id=cw.Reason)  AS [text()] "
			+ "                      From contactwatchlist cw JOIN contact con ON cw.contact=con.id AND con.accountid = payin.accountid "
			+ "                      For XML PATH ('') ) AS WatchListReason, "
			+ "   "
			+ "                      (SELECT NAME "
			+ "                       FROM   organization "
			+ "                       WHERE  id = acc.organizationid) AS organization, "
			+ "                      (SELECT code AS country "
			+ "                       FROM   country "
			+ "                       WHERE  id = (SELECT countryofpayment "
			+ "                                    FROM   paymentinattribute pa "
			+ "                                    WHERE  pa.id = payin.id)) "
			+ "                      AS country, "
			+ "                      (SELECT status "
			+ "                       FROM   paymentcompliancestatusenum "
			+ "                       WHERE  id = (SELECT compliancestatus "
			+ "                                    FROM   paymentin pyi "
			+ "                                    WHERE  payin.id = pyi.id)) "
			+ "                      AS overallstatus, "
			+ "                      acc.WatchlistStatus AS WatchListStatus AS "
			+ "                              watchliststatus, "
			+ "                      (SELECT "
			+ "                        TOP 1 status "
			+ "                       FROM   "
			+ "                         eventservicelog esl "
			+ "                       WHERE  esl.servicetype = (SELECT id FROM compliance_servicetypeenum "
			+ "                                                 WHERE  code = 'BLACKLIST') "
			+ "                              AND payin.id = (SELECT TOP 1 paymentinid FROM event "
			+ "                                              WHERE  id IN ( esl.eventid ) ORDER  BY id DESC)) AS blackliststatus, "
			+ "                      (SELECT TOP 1 status FROM   eventservicelog esl "
			+ "                       WHERE  esl.servicetype = (SELECT id "
			+ "                                                 FROM compliance_servicetypeenum WHERE  code = 'FRAUGSTER') "
			+ "                              AND payin.id = (SELECT TOP 1 paymentinid "
			+ "                                              FROM   event WHERE  id IN ( esl.eventid ) ORDER  BY id DESC)) "
			+ "                      AS fraugsterstatus, "
			+ "                      (SELECT TOP 1 status "
			+ "                       FROM   eventservicelog esl "
			+ "                       WHERE  esl.servicetype = (SELECT id "
			+ "                                                 FROM "
			+ "                              compliance_servicetypeenum "
			+ "                                                 WHERE  code = 'SANCTION') "
			+ "                              AND payin.id = (SELECT TOP 1 paymentinid "
			+ "                                              FROM   event "
			+ "                                              WHERE  id IN ( esl.eventid ) "
			+ "                                              ORDER  BY id DESC)) "
			+ "                      AS "
			+ "                              sanctionstatus , "
			+ "                    ( SELECT TOP 1 status  FROM     eventservicelog esl  WHERE    esl.servicetype = "
			+ "                    ( SELECT id FROM   compliance_servicetypeenum WHERE  code = 'VELOCITYCHECK') AND payin.id = "
			+ "                    (select top 1 paymentinid from event where id in (esl.eventid) order by id desc)) AS CustomCheckStatus "
			+ "                                "
			+ "               FROM   paymentin payIn "
			+ "                      JOIN paymentinattribute payinattri "
			+ "                        ON payin.id = payinattri.id "
			+ "                      JOIN account acc "
			+ "                        ON payin.accountid = acc.id "
			+ "                      JOIN contact con "
			+ "                        ON payin.contactid = con.id "
			+ "                         LEFT JOIN ContactAttribute conattrib "
			+ "                            ON        con.id = conattrib.id "
			+ "                      JOIN PaymentComplianceStatusEnum statusEnum "
			+ "                        ON payin.ComplianceStatus = statusEnum.id "
			+ "                     "
			+ "                      LEFT JOIN userresourcelock ur "
			+ "                             ON payin.id = ur.resourceid "
			+ "                                AND ur.resourcetype = 'PAYMENT_IN' "
			+ "                                AND ur.lockreleasedon IS NULL) AS pqueue "
			+ "                          where  deleted <> 1) AS pqueue2"),
	
	
	GET_PAYMENTIN_REPORT_INNER_QUERY(" SELECT Row_number() OVER ( ORDER BY {SORT_FIELD_NAME} {ORDER_TYPE}) AS rownum, pqueue2.* from "
						+ "       ( SELECT pqueue.* FROM ( select"
			+ " payin.id AS paymentinid, "
			+ " payin.accountid AS accountid, "
			+ " payin.contactid AS contactid, "
			+ " payin.compliancestatus AS compliancestatus, "
			+ " payin.deleted AS deleted, "
			+ " payin.tradecontractnumber AS Transactions, "
			+ " acc.tradeaccountnumber AS client, "
			+ " payinattri.transactiondate AS [Date], "
			+ " acc.[type] AS [type], "
			+ " case when  acc.[type]='PFX' then con.NAME when acc.[type]='CFX' then acc.NAME "
			+ " END as clientname,"
			+ " acc.CRMAccountID AS ACSFID ,  conattrib.Attributes As  ContactAttributes, "
			+ " payinattri.transactioncurrency AS sell, "
			+ " payinattri.transactionamount AS amount, "
			+ " payinattri.paymentmethod AS [method], "
			+ " ur.id AS resourceid, "
			+ " us.ssouserid AS lockedby, "
			+ " org.NAME AS organization, "
			+ " ( Select ','+(select wl.reason AS WatchListReason from WatchList wl where id=cw.Reason)  AS [text()] "
			+ " From contactwatchlist cw JOIN contact con ON cw.contact=con.id AND con.accountid = payin.accountid "
			+ " For XML PATH ('') ) AS WatchListReason, "
			+ " ctr.code AS country, ctr.DisplayName AS CountryDisplayName, "
			+ " pcse.status AS overallstatus,  "
			+ " acc.WatchlistStatus AS watchliststatus ,"
			+ " payin.BlacklistStatus AS blackliststatus, "
			+ " payin.FraugsterStatus AS fraugsterstatus, "
			+ " payin.SanctionStatus AS sanctionstatus, "
			+ " payin.CustomCheckStatus AS CustomCheckStatus "
			+ " FROM "
			+ " paymentin payIn "
			+ " JOIN paymentinattribute payInAttri ON payin.id = payinattri.id "
			+ " JOIN account acc ON payin.accountid = acc.id "
			+ " JOIN contact con ON payin.contactid = con.id "
			+ " JOIN paymentcompliancestatusenum pcse ON payin.compliancestatus = pcse.id "
			+ " LEFT JOIN Country ctr ON payInAttri.countryofpayment = ctr.id "
			+ " JOIN organization org ON org.id = acc.organizationid " 
			+ " LEFT JOIN contactattribute conattrib  ON con.id = conattrib.id "
			+ " LEFT JOIN userresourcelock ur ON payin.id = ur.resourceid "
			+ " AND ur.resourcetype = 'PAYMENT_IN' AND ur.LockReleasedOn IS NULL "
			+ " LEFT JOIN [user] us ON us.id = ur.createdby "
			+ " WHERE "
			+ " {PAYMENTIN_DATETIME_CRITERIA} "
			+ " payIn.deleted = 0  )  As pqueue"),
	
	
	GET_PAYMENTIN_REPORT_PAGINATION_WITH_CRITERIA("WITH pique  "
			+ "AS "
			+ "( {INNER_QUERY} ) "
			+ "  As pqueue2 ) SELECT *, (SELECT max(rownum) FROM pique) AS 'TotalRows' "
			+ " FROM pique WHERE rownum >= ? AND rownum <= ?  "),
	
	GET_PAYMENT_IN_DETAILS("SELECT pyi.id, "
			+ " pyi.accountid, "
			+ " pyi.contactid, "
			+ " org.NAME                               AS Organisation, "
			+ " pyi.TradeContractNumber, "
			+ " (SELECT status FROM  paymentcompliancestatusenum "
			+ " WHERE  id = pyi.compliancestatus)   AS PaymentInStaus, "
			+ " pia.PaymentMethod, "
			+ "                                pia.ThirdPartyPayment, "
			+ " pia.DebitorName, "
			+ " pia.attributes                       AS PaymentInAttributes, "
			+ " (SELECT Code "
			+ " FROM   country "
			+ " WHERE  id = pia.CountryOfPayment)   AS Country, "
			+ " pia.TransactionAmount                AS Amount, "
			+ " pia.TransactionCurrency              AS SellCurrency, "
			+ " pia.TransactionDate                  AS DateOfPayment, "
			+ " co.NAME                              AS ContactName, "
			+ " co.compliancedoneon                  AS RegComplete, "
			+ " co.createdon                         AS RegIn, "
			+ " (SELECT status FROM  contactcompliancestatusenum "
			+ " WHERE  id = co.compliancestatus)    AS ContactComplianceStatus, "
			+ " co.tradecontactid                    AS TradeContactId, "
			+ " pyi.tradepaymentid, "
			+ " coa.attributes                       AS contactAttrib, "
			+ " (SELECT status FROM  accountcompliancestatusenum "
			+ " WHERE  id = acc.compliancestatus)   AS AccComplianceStatus, "
			+ " acc.crmaccountid, "
			+ " acc.tradeaccountnumber, "
			+ " accAttrib.attributes                 AS AccountAttrib, "
			+ " co.crmcontactid, "
			+ " ur.id                                AS userResourceLockId, "
			+ " ur.createdby                         AS LockedBy, "
			+ " esl.id                               AS EventServiceLogId, "
			+ " esl.entityid, "
			+ " (SELECT TOP 1 code "
			+ " FROM   compliance_servicetypeenum "
			+ " WHERE  id = esl.servicetype)        AS ServiceType, "
			+ " esl.entitytype, "
			+ " esl.eventid, "
			+ " esl.summary, "
			+ " esl.status                           AS EventServiceStatus, "
			+ " esl.updatedby                        AS EventServiceUpdatedBy, "
			+ " esl.updatedon                        AS EventServiceUpdatedOn "
			+ " FROM   (SELECT pyi.* "
			+ " FROM   paymentin pyi "
			+ " WHERE  id = ?) AS pyi "
			+ " LEFT JOIN organization org "
			+ " ON pyi.organizationid = org.id "
			+ " LEFT JOIN paymentinattribute pia "
			+ " ON pia.id = pyi.id "
			+ " LEFT JOIN contact co "
			+ " ON co.id = pyi.contactid "
			+ " LEFT JOIN contactattribute coa "
			+ " ON coa.id = pyi.contactid "
			+ " LEFT JOIN account acc "
			+ " ON acc.id = pyi.accountid "
			+ " LEFT JOIN accountattribute accAttrib "
			+ " ON accAttrib.id = pyi.accountid "
			+ " LEFT JOIN eventservicelog esl "
			+ " ON esl.id IN (SELECT ESL.id AS logid "
			+ " FROM   [eventservicelog] ESL "
			+ " JOIN event EV "
			+ " ON ESL.eventid = EV.id "
			+ " AND EV.paymentoutid IS NULL "
			+ " WHERE  EV.paymentinid = ?) "
			+ " LEFT JOIN userresourcelock ur "
			+ " ON pyi.id = ur.resourceid "
			+ " AND ur.lockreleasedon IS NULL "
			+ " AND ur.resourcetype = 'PAYMENT_IN' "
			+ " ORDER  BY esl.servicetype, "
			+ " ESL.updatedon DESC"),
	
	 GET_PAYMNETIN_REPORT_WHOLE_DATA( "select rc.* "
				+ "from( {INNER_QUERY}"
				+ " )as pqueue2 )as rc"
				);
	
	
	private String query;

	PaymentInReportQueryConstant(String query) {
		this.query = query;

	}

	public String getQuery() {
		return this.query;
	}

}