USE [master]

CREATE DATABASE [Compliance]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'Compliance', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ComplianceStructureChange.mdf' , SIZE = 16777216KB , MAXSIZE = UNLIMITED, FILEGROWTH = 524288KB ),
 FILEGROUP [Ftsi]
( NAME = N'Compliance_Ftsi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Compliance_Ftsi.ndf' , SIZE = 4194304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 524288KB ),
 FILEGROUP [Idx]
( NAME = N'Compliance_Idx', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Compliance_Idx.ndf' , SIZE = 4194304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 524288KB )
 LOG ON
( NAME = N'Compliance_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ComplianceStructureChange_1.ldf' , SIZE = 6029312KB , MAXSIZE = 2048GB , FILEGROWTH = 262144KB )
ALTER DATABASE [Compliance] SET COMPATIBILITY_LEVEL = 130

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Compliance].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [Compliance] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [Compliance] SET ANSI_NULLS OFF 

ALTER DATABASE [Compliance] SET ANSI_PADDING OFF 

ALTER DATABASE [Compliance] SET ANSI_WARNINGS OFF 

ALTER DATABASE [Compliance] SET ARITHABORT OFF 

ALTER DATABASE [Compliance] SET AUTO_CLOSE OFF 

ALTER DATABASE [Compliance] SET AUTO_SHRINK OFF 

ALTER DATABASE [Compliance] SET AUTO_UPDATE_STATISTICS ON 

ALTER DATABASE [Compliance] SET CURSOR_CLOSE_ON_COMMIT OFF 

ALTER DATABASE [Compliance] SET CURSOR_DEFAULT  GLOBAL 

ALTER DATABASE [Compliance] SET CONCAT_NULL_YIELDS_NULL OFF 

ALTER DATABASE [Compliance] SET NUMERIC_ROUNDABORT OFF 

ALTER DATABASE [Compliance] SET QUOTED_IDENTIFIER OFF 

ALTER DATABASE [Compliance] SET RECURSIVE_TRIGGERS OFF 

ALTER DATABASE [Compliance] SET  DISABLE_BROKER 

ALTER DATABASE [Compliance] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 

ALTER DATABASE [Compliance] SET DATE_CORRELATION_OPTIMIZATION OFF 

ALTER DATABASE [Compliance] SET TRUSTWORTHY OFF 

ALTER DATABASE [Compliance] SET ALLOW_SNAPSHOT_ISOLATION OFF 

ALTER DATABASE [Compliance] SET PARAMETERIZATION SIMPLE 

ALTER DATABASE [Compliance] SET READ_COMMITTED_SNAPSHOT OFF 

ALTER DATABASE [Compliance] SET HONOR_BROKER_PRIORITY OFF 

ALTER DATABASE [Compliance] SET RECOVERY SIMPLE 

ALTER DATABASE [Compliance] SET  MULTI_USER 

ALTER DATABASE [Compliance] SET PAGE_VERIFY CHECKSUM  

ALTER DATABASE [Compliance] SET DB_CHAINING OFF 

ALTER DATABASE [Compliance] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 

ALTER DATABASE [Compliance] SET TARGET_RECOVERY_TIME = 0 SECONDS 

ALTER DATABASE [Compliance] SET DELAYED_DURABILITY = DISABLED 

EXEC sys.sp_db_vardecimal_storage_format N'Compliance', N'ON'

ALTER DATABASE [Compliance] SET QUERY_STORE = OFF