package com.currenciesdirect.gtg.compliance.util;

/**
 * The Enum RequestTypes.
 */
public enum RequestTypes {
	
	SIGNUP_PFX,
	ADD_CONTACT_PFX,
	UPDATE_ACCOUNT_PFX,
	SIGNUP_CFX,
	ADD_CONTACT_CFX,
	UPDATE_ACCOUNT_CFX,
	PAYMENT_IN,
	PAYMENT_OUT,
	SHOW_BLACKLIST_DATA,
	ADD_BLACKLIST_DATA,
	DELETE_BLACKLIST_DATA,
	SEARCH_BLACKLIST_DATA,
	BLACKLIST_RECHECK,
	PAYMENT_OUT_PAY_REF;

}
