package com.currenciesdirect.gtg.compliance.compliancesrv.core;

public enum OperationEnum {
	
	NEW_REGISTRATION,
	ADD_CONTACT,
	UPDATE_ACCOUNT,
	KYC_RESEND,
	SANCTION_RESEND,
	SANCTION_UPDATE,
	DOCUMENT_UPLOAD,
	CONTACT_STATUS,
	FUNDS_OUT,
	UPDATE_OPI,
	DELETE_OPI,
	FUNDS_IN,
	CUSTOMCHECK_RESEND,
	FRAUGSTER_RESEND,
	WHITELIST_UPDATE,
	BLACKLIST_RESEND,
	RECHECK_FAILURES, 
	STATUS_UPDATE,
	DELETE_CONTACT,
	ONFIDO_STATUS_UPDATE,
	DATA_ANONYMIZE,
	PAYMENT_REFERENCE_RESEND,
	TRANSACTION_MONITORING_MQ_RESEND,
	REPEAT_CHECK_STATUS_UPDATE,
	CHECK_CARD_ELIGIBILITY,
	CARD_STATUS_UPDATE,
	POST_TRANSACTION,
	GET_PAYMENT_STATUS
}


/*
PROFILE.NEW_REGISTRATION.in.channel
PROFILE.ADD_CONTACT.in.channel
PROFILE.UPDATE_CONTACT.in.channel
PROFILE.UPDATE_ACCOUNT.in.channel
PROFILE.KYC_RESEND.in.channel
PROFILE.SANCTION_RESEND.in.channel
PROFILE.DOCUMENT_UPLOAD.in.channel
PROFILE.REGISTRATION_ENQUIRY.in.channel
PROFILE.CONTACT_STATUS.in.channel
*/