package communicationapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-10-08T14:41:21.119+05:30
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "CommunicationAPI", 
                  wsdlLocation = "file:CommunicationAPI.wsdl",
                  targetNamespace = "urn:CommunicationAPI") 
@SuppressWarnings("squid:S00101")
public class CommunicationAPI_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("urn:CommunicationAPI", "CommunicationAPI");
    public static final QName CommunicationAPIPort = new QName("urn:CommunicationAPI", "CommunicationAPIPort");
    static {
        URL url = null;
        try {
            url = new URL("file:CommunicationAPI.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CommunicationAPI_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:CommunicationAPI.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CommunicationAPI_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CommunicationAPI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommunicationAPI_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CommunicationAPI_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CommunicationAPI_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CommunicationAPI_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CommunicationAPI
     */
    @WebEndpoint(name = "CommunicationAPIPort")
    public CommunicationAPI getCommunicationAPIPort() {
        return super.getPort(CommunicationAPIPort, CommunicationAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommunicationAPI
     */
    @WebEndpoint(name = "CommunicationAPIPort")
    public CommunicationAPI getCommunicationAPIPort(WebServiceFeature... features) {
        return super.getPort(CommunicationAPIPort, CommunicationAPI.class, features);
    }

}
